#!/usr/bin/env python3
"""Build docs/experiments/ATLAS.md — a categorized overview of every experiment,
grouped by `approach_family`, from the per-experiment files docs/experiments/<exp_id>.md.

Each per-exp file carries a YAML-ish frontmatter (see /exp-log) with: exp_id,
date, approach_family, parent_exp, track, profile, status, primary_metric, value,
vs_anchor, one_liner. This deterministically renders, per family, a table + a
best-of-family + a lineage chain, so the whole exploration tree is visible at a
glance. Pure stdlib. Idempotent. Run after /exp-log writes a new per-exp file.
"""
import os, re, sys, glob

ROOT = sys.argv[1] if len(sys.argv) > 1 else (os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd())
EXPDIR = os.path.join(ROOT, "docs", "experiments")
FIELDS = ("exp_id", "date", "approach_family", "parent_exp", "track", "profile",
          "status", "primary_metric", "value", "vs_anchor", "one_liner")


def parse(path):
    txt = open(path, encoding="utf-8").read()
    m = re.match(r"^---\n(.*?)\n---", txt, re.S)
    if not m:
        return None
    d = {}
    for line in m.group(1).splitlines():
        mm = re.match(r"^(\w+):\s*(.*)$", line.strip())
        if mm:
            d[mm.group(1)] = mm.group(2).strip().strip('"').strip("'")
    if "exp_id" not in d:
        d["exp_id"] = os.path.splitext(os.path.basename(path))[0]
    return d


def main():
    if not os.path.isdir(EXPDIR):
        print(f"no {EXPDIR} — nothing to atlas", file=sys.stderr); return
    exps = []
    for p in sorted(glob.glob(os.path.join(EXPDIR, "*.md"))):
        if os.path.basename(p) == "ATLAS.md":
            continue
        d = parse(p)
        if d:
            exps.append(d)
    if not exps:
        print("no per-exp files yet", file=sys.stderr); return

    fams = {}
    for e in exps:
        fams.setdefault(e.get("approach_family", "uncategorized"), []).append(e)

    out = ["# Experiment Atlas (auto-generated by scripts/build_atlas.py — do not hand-edit)",
           "", f"> {len(exps)} experiments across {len(fams)} approach families. "
           "Per-experiment detail: `docs/experiments/<exp_id>.md`. Regenerate: `python3 scripts/build_atlas.py`.", ""]
    # families first (spike/uncategorized last)
    def order(k):
        return (1 if k in ("spike", "uncategorized") else 0, k)
    for fam in sorted(fams, key=order):
        rows = sorted(fams[fam], key=lambda e: (e.get("date", ""), e.get("exp_id", "")))
        out.append(f"## {fam}  ({len(rows)} exp)")
        out.append("")
        out.append("| exp_id | one_liner | metric | vs | status | ← parent |")
        out.append("|---|---|---|---:|---|---|")
        best = None
        for e in rows:
            v = e.get("value", "")
            out.append(f"| {e.get('exp_id','?')} | {e.get('one_liner','')} | "
                       f"{e.get('primary_metric','')}={v} | {e.get('vs_anchor','')} | "
                       f"{e.get('status','')} | {e.get('parent_exp','-')} |")
            try:
                fv = float(v)
                if best is None or fv > best[1]:
                    best = (e.get("exp_id"), fv)
            except (ValueError, TypeError):
                pass
        if best:
            out.append(f"\n_best-of-family: **{best[0]}** ({best[1]})_")
        # lineage chains
        chains = []
        for e in rows:
            par = e.get("parent_exp", "-")
            if par and par != "-":
                chains.append(f"{par} → {e.get('exp_id')}")
        if chains:
            out.append("\nlineage: " + " ; ".join(chains))
        out.append("")
    atlas = os.path.join(EXPDIR, "ATLAS.md")
    open(atlas, "w", encoding="utf-8").write("\n".join(out) + "\n")
    print(f"✓ atlas: {len(exps)} exps, {len(fams)} families → {atlas}")


if __name__ == "__main__":
    main()
